In [8]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [34]:
from numpy.random import randn
import numpy as np
import os
from dad_torch.distrib import DadHook

In [13]:
N, D_in, H, D_out = 16, 6, 5, 2

In [56]:
mid = N//2

In [57]:
np.random.seed(1)
x = randn(N, D_in)
np.random.seed(2)
y = randn(N, D_out)

x1, x2 = x[:mid], x[mid:]
y1, y2 = y[:mid], y[mid:]

In [58]:
np.random.seed(3)
w1 = randn(D_in, H) 
np.random.seed(4)
w2 = randn(H, D_out)
w1.shape, w2.shape

((6, 5), (5, 2))

In [59]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.Linear(6, 5, bias=False)
        self.bn = nn.BatchNorm1d(5)
        self.l2 = nn.Linear(5, 2, bias=False)
        
    def forward(self, x):
        x = torch.sigmoid(self.l1(x))
        x = self.bn(x)
        x= self.l2(x)
        return x

In [60]:
net = DadHook(Net())
net.train()

DadHook(
  (module): Net(
    (l1): Linear(in_features=6, out_features=5, bias=False)
    (bn): BatchNorm1d(5, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (l2): Linear(in_features=5, out_features=2, bias=False)
  )
)

In [61]:
# def hook_wrapper(site, hook_type, layer, save_to='', debug=False):
#     if debug:
#         print(f"**** {site}, {hook_type}, {layer} ****")

#     name = os.path.join(save_to, f"Site:{site}-Type:{hook_type}-Layer:{layer}")

#     def hook_save(a, in_grad, out_grad):
#         if hook_type.lower() == 'forward':
#             for i, b in enumerate(in_grad):
#                 if b is not None:
#                     np.save(name + f"-IO:in-Index:{i}.npy", b.clone().detach().numpy())
#                 break
#         if hook_type.lower() == 'backward':
#             for i, c in enumerate(out_grad):
#                 if c is not None:
#                     np.save(name + f"-IO:out-index:{i}.npy", c.clone().detach().numpy())
#                 break

#     return hook_save

In [23]:
for t in range(10):
    h = 1/(1+np.exp(-x.dot(w1)))
    print('h:', h.shape)
    y_pred = h.dot(w2)
    loss = np.square(y_pred-y).sum()
#     print(t, loss)
    
    grad_y_pred = 2.0 * (y_pred - y)
    print('grad_y_pred:', grad_y_pred.shape)
    
    grad_w2 = h.T.dot(grad_y_pred)
    print('grad_w2: ', grad_w2.shape)
    
    
    grad_h = grad_y_pred.dot(w2.T)
    print('grad_h: ', grad_h.shape)
    grad_w1 = x.T.dot(grad_h * h * (1-h))
    print('grad_w1:', grad_w1.shape)
    
    w1 -= 1e-4 * grad_w1
    w2 -= 1e-4 * grad_w2
    break

h: (16, 5)
grad_y_pred: (16, 2)
grad_w2:  (5, 2)
grad_h:  (16, 5)
grad_w1: (6, 5)


In [62]:
p1 = net(torch.Tensor(x))

/home/ak/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:974: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "


In [63]:
loss = torch.square(p1-torch.Tensor(y)).sum()

In [65]:
loss.backward()

In [71]:
act = net._activations['bn']

In [80]:
grad = net._local_grads['bn']

In [81]:
act.shape, grad.shape

(torch.Size([16, 5]), torch.Size([16, 5]))

In [123]:
ch = list(net.module.children())

In [137]:
for c in ch:
    print(isinstance(c, nn.BatchNorm1d))

False
True
False


In [82]:
vars(ch[1])

{'training': True,
 '_parameters': OrderedDict([('weight', Parameter containing:
               tensor([1., 1., 1., 1., 1.], requires_grad=True)),
              ('bias',
               Parameter containing:
               tensor([0., 0., 0., 0., 0.], requires_grad=True))]),
 '_buffers': OrderedDict([('running_mean',
               tensor([0.0472, 0.0526, 0.0464, 0.0501, 0.0480])),
              ('running_var',
               tensor([0.9014, 0.9002, 0.9022, 0.9021, 0.9016])),
              ('num_batches_tracked', tensor(1))]),
 '_non_persistent_buffers_set': set(),
 '_backward_hooks': OrderedDict([(36,
               <function dad_torch.distrib.utils.DadHook._hook_fn.<locals>.get(m, in_grad, out_grad)>)]),
 '_is_full_backward_hook': False,
 '_forward_hooks': OrderedDict([(35,
               <function dad_torch.distrib.utils.DadHook._hook_fn.<locals>.get(m, in_grad, out_grad)>)]),
 '_forward_pre_hooks': OrderedDict(),
 '_state_dict_hooks': OrderedDict(),
 '_load_state_dict_pre_hooks': Or

In [89]:
params = list(net.named_parameters())

In [94]:
params[1][1].grad

tensor([ 9.1606,  2.1797,  1.8189, -0.2858,  5.2030])

In [112]:
dbeta =  params[2][1].grad.detach()

In [109]:
grad.shape, act.shape

(torch.Size([16, 5]), torch.Size([16, 5]))

In [105]:
(act.T.mm(grad)).sum(0)

tensor([ 8.1682, 11.4447,  3.0139,  9.8893, -3.6210], grad_fn=<SumBackward1>)

In [121]:
var = (grad * act).sum(0)

In [27]:
for k, p in net.named_parameters():
    print(k,p)

l1.weight Parameter containing:
tensor([[ 1.7886, -0.3548, -1.3139, -0.4047, -1.1850, -0.7130],
        [ 0.4365, -0.0827,  0.8846, -0.5454, -0.2056,  0.6252],
        [ 0.0965, -0.6270,  0.8813, -1.5465,  1.4861, -0.1605],
        [-1.8635, -0.0438,  1.7096,  0.9824,  0.2367, -0.7688],
        [-0.2774, -0.4772,  0.0500, -1.1011, -1.0238, -0.2300]],
       requires_grad=True)
l2.weight Parameter containing:
tensor([[ 0.0506, -0.9959, -0.4183, -0.6477,  0.3323],
        [ 0.5000,  0.6936, -1.5846,  0.5986, -1.1475]], requires_grad=True)


In [23]:
n = Net()

In [26]:
for p in net.parameters():
    p.grad.detach_()

In [32]:
n.load_state_dict(torch.load('chk.tar'))

<All keys matched successfully>

In [37]:
"Name: {}".format('AK')

'Name: AK'

In [44]:
t = torch.FloatTensor([[1, 2], [3, 4]], device='cpu')

In [45]:
t.T.mm()

tensor([[1., 3.],
        [2., 4.]])

In [46]:
t

tensor([[1., 2.],
        [3., 4.]])

In [50]:
h.T.dot(grad_y_pred)

array([[ -3.65050639, -20.05829342],
       [ -8.77522329, -11.72429864],
       [ -5.49211195, -17.99616749],
       [ -7.0682281 ,  -3.19438619],
       [ -7.95513326, -15.59246294]])

In [52]:
torch.Tensor(h).T.mm(torch.Tensor(grad_y_pred))

tensor([[ -3.6505, -20.0583],
        [ -8.7752, -11.7243],
        [ -5.4921, -17.9962],
        [ -7.0682,  -3.1944],
        [ -7.9551, -15.5925]])

In [55]:
[p.grad.shape for p in net.parameters()]

[torch.Size([5, 6]), torch.Size([2, 5])]

In [64]:
for l, ch in net.named_parameters():
    print(l, ch.grad)

l1.weight tensor([[-0.1147,  0.2385, -0.1600,  2.0195,  0.8291,  0.4634],
        [-5.2419,  3.7720,  1.7932,  3.2138, -1.9054,  4.8540],
        [ 0.9208, -0.0698, -1.5408, -6.1658, -2.3991, -0.7603],
        [-1.2793,  2.9918,  0.6647,  0.7110, -1.0412,  3.3018],
        [ 6.0451, -2.3750, -1.7649, -4.2975,  2.3372, -5.0113]])
l2.weight tensor([[ -3.6777,  -8.8142,  -5.5268,  -7.0952,  -7.9853],
        [-20.1403, -11.7940, -18.0874,  -3.2346, -15.6785]])


In [215]:

def _hierarchy_key(*args):
    return ".".join([f"{a}" for a in args])


class DADParallel(torch.nn.Module):
    def __init__(self, module, device=None, reduction_method='dad', reduction_rank=5, num_pow_iters=1, **kw):
#         assert _dist.is_initialized(), "*** Default process group is not initialized. ***"

        super(DADParallel, self).__init__()
        self.module = module
        self.device = device
        self.cache = kw.get('cache', {})
        self.reduction_method = reduction_method
        self.reduction_rank = reduction_rank
        self.num_pow_iters = num_pow_iters
        self.commn_mode = kw.get('commn_mode', 'all_gather')
        self._reset()

    def _reset(self):
        self.fw_hooks_handle = []
        self.bk_hooks_handle = []
        self._activations = {}
        self._local_grads = {}

    def _hook_fn(self, hook_type, hook_key):
        def get(m, in_grad, out_grad):
            if hook_type.lower() == 'forward':
                for i, b in enumerate(in_grad):
                    if b is not None:
                        self._activations[hook_key] = b
                    break
            if hook_type.lower() == 'backward':
                for i, c in enumerate(out_grad):
                    if c is not None:
                        self._local_grads[hook_key] = c
                    break

        return get

    def _hook(self):
        def _hook_recursive(module_name, module):
            children = list(module.named_children())[::-1]
            if len(children) > 0:
                for children_name, child in children:
                    _hook_recursive(_hierarchy_key(module_name, children_name), child)
            elif len(list(module.parameters())) > 0:
                self.fw_hooks_handle.append(
                    module.register_forward_hook(self._hook_fn('forward', module_name))
                )
                self.bk_hooks_handle.append(
                    module.register_backward_hook(self._hook_fn('backward', module_name))
                )

        if self.training:
            for ch_name, ch in list(self.module.named_children())[::-1]:
                _hook_recursive(ch_name, ch)

    def _unhook(self):
        for hk in self.fw_hooks_handle:
            hk.remove()
        for hk in self.bk_hooks_handle:
            hk.remove()

    def train(self, mode=True):
        self.module.train(mode)
        self._hook()
        return self

    def eval(self):
        self.module.eval()
        self._unhook()
        return self

    def forward(self, *inputs, **kwargs):
        if self.training:
            self._reset()
        output = self.module(*inputs, **kwargs)
        return output

In [223]:
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.lo = nn.Linear(64, 32)
        self.decoder = nn.Sequential(nn.Linear(32, 16), nn.ReLU(), nn.Linear(16, 6), nn.ReLU())
        self.l1 = nn.Linear(6, 5, bias=False)
        self.l2 = nn.Linear(5, 2, bias=False)
        
    def forward(self, x):
        x = torch.sigmoid(self.lo(x))
        x = self.decoder(x)
        x= torch.sigmoid(self.l1(x))
        x = self.l2(x)
        return x

In [224]:
n = Net()
dnet = DADParallel(n)

In [225]:
dnet.train()

DADParallel(
  (module): Net(
    (lo): Linear(in_features=64, out_features=32, bias=True)
    (decoder): Sequential(
      (0): Linear(in_features=32, out_features=16, bias=True)
      (1): ReLU()
      (2): Linear(in_features=16, out_features=6, bias=True)
      (3): ReLU()
    )
    (l1): Linear(in_features=6, out_features=5, bias=False)
    (l2): Linear(in_features=5, out_features=2, bias=False)
  )
)

In [220]:
x = torch.randn(4, 64)

In [221]:
o = dnet(x)

/home/ak/.local/lib/python3.8/site-packages/torch/nn/modules/module.py:974: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "


In [222]:
dnet._activations

{'lo': tensor([[-0.4835, -1.1069, -0.7140, -0.8197, -0.0525,  0.1120,  1.7470,  1.1938,
           0.1551, -0.6305,  0.6991, -0.4405,  0.6725, -1.8085,  0.5469, -0.8451,
          -2.0803, -0.7865, -0.3121, -0.8956,  1.6029,  0.5956, -0.4439,  0.9837,
          -0.7879,  2.0132, -1.3898, -0.1196, -0.4305,  0.3405,  0.0573,  1.7856,
           0.7943,  0.0197,  1.3671, -1.8850,  0.7181, -0.3402, -0.5229, -0.1278,
          -1.3658, -0.9323, -1.4480,  0.3277, -0.4665, -1.0870,  0.9598, -0.5879,
           0.8310,  0.8189,  0.7159, -1.8115,  0.0307,  1.1331,  0.6225,  0.6362,
           0.2708, -0.0050, -0.9191,  1.0267, -0.0897,  1.7244, -1.7051, -0.9401],
         [-0.4094, -0.7636, -0.1106,  1.0749,  0.2856,  1.5373,  0.1219, -0.1334,
          -1.8924, -1.1252, -0.8243, -0.8567, -0.4680, -1.0060,  1.4966, -0.9700,
          -1.3467,  0.3709,  1.9041, -0.1403, -0.2137, -1.8996, -1.3642,  1.5709,
           0.6732,  0.5717, -0.2123, -0.7953, -0.3978,  1.2180, -1.5668,  0.6420,
         

In [192]:
net = nn.Sequential(nn.Linear(100, 50), nn.ReLU(), nn.Linear(50, 10))

In [194]:
dict(net.named_children())

{'0': Linear(in_features=100, out_features=50, bias=True),
 '1': ReLU(),
 '2': Linear(in_features=50, out_features=10, bias=True)}

In [201]:
list(dnet.module.named_children())

[('lo', Linear(in_features=64, out_features=32, bias=True)),
 ('decoder',
  Sequential(
    (0): Linear(in_features=32, out_features=16, bias=True)
    (1): ReLU()
    (2): Linear(in_features=16, out_features=6, bias=True)
    (3): ReLU()
  )),
 ('l1', Linear(in_features=6, out_features=5, bias=False)),
 ('l2', Linear(in_features=5, out_features=2, bias=False))]